### ISSUE TITLE
使用recompute 环境变量无法使用tf.saved

### ISSUE THREAD

**Issue by luoy2** [bojone/bert4keras#139]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  windows 10
- 你使用的**Python**版本:  3.7.7
- 你使用的**Tensorflow**版本:  2.1.0
- 你使用的**Keras**版本:  2.2.4-tf
- 你使用的**bert4keras**版本: 0.7.5
- 你使用纯**keras**还是**tf.keras**: tf.keras 
- 你加载的**预训练模型**: simbert_base

### 核心代码
```python
import os
os.environ['RECOMPUTE'] = '1'
bert = build_transformer_model(
            config_path=bert_config_path,
            checkpoint_path=bert_checkpoint_path,
            model='bert',
            with_pool=True,
            return_keras_model=True,
        )
tf.saved_model.save(bert.model, os.path.dirname(model_path))
```

### 输出信息
```shell
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-306-4ebee3f2de71>", line 1, in <module>
    tf.saved_model.save(bert.model, os.path.dirname(model_path))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 886, in save
    checkpoint_graph_view)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\saved_model\signature_serialization.py", line 74, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\saved_model\save.py", line 142, in list_functions
    self._serialization_cache)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2420, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\base_serialization.py", line 91, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\layer_serialization.py", line 80, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 172, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 513, in add_function
    self.add_trace(*self._input_signature)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 428, in add_trace
    trace_with_training(True)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 426, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 557, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 909, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 497, in _initialize
    *args, **kwds))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 534, in wrapper
    ret = method(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 113, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\framework\smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 112, in <lambda>
    lambda: replace_training_and_call(True),
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 108, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 576, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 59, in return_outputs_and_add_losses
    outputs, losses = fn(inputs, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 113, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\framework\smart_cond.py", line 54, in smart_cond
    return true_fn()
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 112, in <lambda>
    lambda: replace_training_and_call(True),
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\utils.py", line 108, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 551, in __call__
    self.call_collection.add_trace(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 428, in add_trace
    trace_with_training(True)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 426, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 557, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 909, in get_concrete_function
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 497, in _initialize
    *args, **kwds))
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 523, in wrapper
    inputs = call_collection.get_input_arg_value(args, kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\saving\saved_model\save_impl.py", line 463, in get_input_arg_value
    self._input_arg_name, args, kwargs, inputs_in_args=True)
  File "C:\ProgramData\Anaconda3\envs\tf2gpu\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 1991, in _get_call_arg_value
    return args_dict[arg_name]
KeyError: 'inputs'
model.save_weights(model_path)

```

### 自我尝试
如果不适用os.environ['RECOMPUTE'] = '1'可正常保存。

不知道是否与tf本身有关

[Cannot save to SavedModel when custom layers accepts args and kwargs](https://github.com/tensorflow/tensorflow/issues/38384)

我觉得现解决方案可以使用recompute训练， 只保存weight； 训练完成后另起一个recompute=-1的脚本，load_weight后save 模型。

**Comment by bojone** [comment]
我调试调试看看

**Comment by bojone** [comment]
已经修复了。 https://github.com/bojone/bert4keras/commit/b53c2e3c13a359d2f056d9c80d017ada3f59dbf7
