### ISSUE TITLE
接 Conv1D 提示不支持

### ISSUE THREAD

**Issue by jerrysjin** [bojone/bert4keras#151]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Linux
- 你使用的**Python**版本: 3.6
- 你使用的**Tensorflow**版本: 2.1
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**: 0.7.0
- 你加载的**预训练模型**: Albert

### 核心代码
```python
albert = build_transformer_model(
            config_path = config['model_config_path'],
            checkpoint_path = config['checkpoint_path'],
            model = 'albert',
            return_keras_model = False
            )
output = Conv1D(
            filters = 2 * config['hidden_size'],
            kernel_size = 3
            )(output)
```

### 输出信息
```shell
TypeError: Layer conv1d_1 does not support masking, but was passed an input_mask: Tensor("Transformer-FeedForward-Add_5/All:0", shape=(None, None), dtype=bool)
```

作为downstrea task，请问如何接1d的卷积层呢？

**Comment by yiyangiliu** [comment]
看输出信息，因为Cov1D不支持mask。

我感觉 只要在类里加上`self.supports_masking=True`就能避免报错。

其实这个问题作者已经在他写的类里避免了，通过[魔改keras.layers.Layer](https://github.com/bojone/bert4keras/blob/master/bert4keras/layers.py#L33-L39)的方式。

你可以仿照作者，魔改一下Conv1D，类似这样：

```python
class myConv1D(keras.layers.Conv1D):
    def __init__(self, **kwargs):
        super(myConv1D, self).__init__(**kwargs)
        self.supports_masking = True 
```
然后把代码改成:
```python
output = myConv1D(...)(output)
```

**Comment by jerrysjin** [comment]
> 看输出信息，因为Cov1D不支持masking。
> 
> 我感觉 只要在类里加上`self.supports_masking=True`就能避免报错。
> 
> 其实这个问题作者已经在他写的类里避免了，通过[魔改keras.layers.Layer](https://github.com/bojone/bert4keras/blob/master/bert4keras/layers.py#L33-L39)的方式。
> 
> 你可以仿照作者，魔改一下Conv1D，类似这样：
> 
> ```python
> class myConv1D(keras.layers.Conv1D):
>     def __init__(self, **kwargs):
>         super(myConv1D, self).__init__(**kwargs)
>         self.supports_masking = True 
> ```
> 
> 然后把代码改成:
> 
> ```python
> output = myConv1D(...)(output)
> ```



> 看输出信息，因为Cov1D不支持masking。
> 
> 我感觉 只要在类里加上`self.supports_masking=True`就能避免报错。
> 
> 其实这个问题作者已经在他写的类里避免了，通过[魔改keras.layers.Layer](https://github.com/bojone/bert4keras/blob/master/bert4keras/layers.py#L33-L39)的方式。
> 
> 你可以仿照作者，魔改一下Conv1D，类似这样：
> 
> ```python
> class myConv1D(keras.layers.Conv1D):
>     def __init__(self, **kwargs):
>         super(myConv1D, self).__init__(**kwargs)
>         self.supports_masking = True 
> ```
> 
> 然后把代码改成:
> 
> ```python
> output = myConv1D(...)(output)
> ```

谢谢！

**Comment by bojone** [comment]
建议这样改

```python
class MyConv1D(keras.layers.Conv1D):
    def __init__(self, *args, **kwargs):
        super(myConv1D, self).__init__(*args, **kwargs)
        self.supports_masking = True 

    def call(self, inputs, mask=None):
        if mask is not None:
            mask = K.cast(mask, K.floatx())
            inputs = inputs * mask[:, :, None]
        return super(MyConv1D, self).call(inputs)
```

**Comment by jerrysjin** [comment]
> 建议这样改
> 
> ```python
> class MyConv1D(keras.layers.Conv1D):
>     def __init__(self, *args, **kwargs):
>         super(MyConv1D, self).__init__(*args, **kwargs)
>         self.supports_masking = True 
> 
>     def call(self, inputs, mask=None):
>         if mask is not None:
>             mask = K.cast(mask, K.floatx())
>             inputs = inputs * mask[:, :, None]
>         return super(MyConv1D, self).call(inputs)
> ```

基于 examples/task_sentiment_albert.py 构建的一个简单albert-cnn模型，做二分类问题，模型代码如下：
```python

class ClsfModel(object):
    """ define albert based classifier model
    """
    def __new__(cls, config):
        
        class ModelConv1D(Conv1D):
            def __init__(self, **kwargs):
                super(ModelConv1D, self).__init__(**kwargs)
                self.supports_masking = True
            
            def call(self, inputs, mask = None):
                if mask is not None:
                    mask = K.cast(mask, K.floatx())
                    inputs = inputs * mask[:, :, None]
                return super(ModelConv1D, self).call(inputs)
        
        class ModelGlobalMaxPooling1D(GlobalMaxPooling1D):
            def __init__(self, **kwargs):
                super(ModelGlobalMaxPooling1D, self).__init__(**kwargs)
                self.supports_masking = True
        
        albert = build_transformer_model(
            config_path = config['model_config_path'],
            checkpoint_path = config['checkpoint_path'],
            model = 'albert',
            return_keras_model = False
            )
        
        output = albert.model.output
        output = ModelConv1D(
            filters = 2 * config['gru_hidden_size'],
            kernel_size = 3
            )(output)
        output = ModelGlobalMaxPooling1D()(output)
        
        output = Dense(
            units = config['gru_hidden_size'],
            activation = 'relu',
            kernel_initializer = albert.initializer
            )(output)
        
        output = Dropout(rate = 0.2)(output)
        output = Dense(
            units = config['class_num'],
            activation = 'softmax',
            kernel_initializer = albert.initializer
            )(output)
        
        model = keras.models.Model(albert.model.input, output)
        model.summary()
        
        AdamLR = extend_with_piecewise_linear_lr(Adam)
        
        model.compile(
            loss = 'sparse_categorical_crossentropy',
            optimizer = AdamLR(
                learning_rate = 1e-4,
                lr_schedule = {1000: 1, 10000: 0.1}
                ),
            metrics = ['accuracy']
            )
        
        return model

```
从model.summary()的输出来看，模型结构似乎没有问题。

数据样例
```python

更多酒厂都能出极品质品牌消费会更多选择会感压力\t0
融创收万达入都难常理解释加杠杆豪赌倒更加持信心爆棚会融创推握命运局\t1

```

在执行之后，报错
```python
Epoch 1/2
Traceback (most recent call last):
  File "classifier.py", line 336, in <module>
    callbacks = [evaluator]
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1551, in __call__
    return self._call_impl(args, kwargs)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1591, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Can not squeeze dim[1], expected a dimension of 1, got 90
         [[{{node metrics/accuracy/ArithmeticOptimizer/ReorderCastLikeAndValuePreserving_bool_Squeeze_1}}]] [Op:__inference_keras_scratch_graph_12323]

Function call stack:
keras_scratch_graph
```

如果将downstream model改成双向gru或者lstm就不会有以上错误。

**Comment by yiyangiliu** [comment]
盲猜没把[CLS] token取出

**Comment by bojone** [comment]
这个好像真看不出什么原因～

**Comment by bojone** [comment]
你model.summary( )，把bert以外的部分copy给我看看

**Comment by jerrysjin** [comment]
> 你model.summary( )，把bert以外的部分copy给我看看

```python

__________________________________________________________________________________________________
model_conv1d_1 (ModelConv1D)    (None, None, 256)    295168      Transformer-FeedForward-Norm[5][0
__________________________________________________________________________________________________
model_global_max_pooling1d_1 (M (None, 256)          0           model_conv1d_1[0][0]             
__________________________________________________________________________________________________
dense_7 (Dense)                 (None, 128)          32896       model_global_max_pooling1d_1[0][0
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 128)          0           dense_7[0][0]                    
__________________________________________________________________________________________________
dense_8 (Dense)                 (None, 2)            258         dropout_1[0][0]                  
==================================================================================================
Total params: 4,922,754
Trainable params: 4,922,754
Non-trainable params: 0

```
这是bert以外部分的summary输出

**Comment by bojone** [comment]
感觉上模型没有问题，好像是metrics有问题，你可以在这里打印下`converted_inputs`看看有什么特点
```python
  File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
    outputs = self._graph_fn(*converted_inputs)
```

**Comment by jerrysjin** [comment]
> 感觉上模型没有问题，好像是metrics有问题，你可以在这里打印下`converted_inputs`看看有什么特点
> 
> ```python
>   File "/home/ec2-user/anaconda3/envs/manberries3.6/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3727, in __call__
>     outputs = self._graph_fn(*converted_inputs)
> ```

把batch_size 改成了2以后，打印了一下`converted_inputs`，如果是接的是cnn，输出是
```python

[<tf.Tensor: shape=(2, 17), dtype=float32, numpy=
array([[ 101., 1394.,  830., 5500., 5341., 1394., 2458., 1355.,  965.,
        3326., 2832., 6598., 6369., 1153.,  711.,  891.,  102.],
       [ 101., 5869.,  752.,  833.,  102.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]],
      dtype=float32)>, <tf.Tensor: shape=(2, 17), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [0.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>]

```

如果接的是双向GRU，输出是
```python

[<tf.Tensor: shape=(2, 17), dtype=float32, numpy=
array([[ 101., 1394.,  830., 5500., 5341., 1394., 2458., 1355.,  965.,
        3326., 2832., 6598., 6369., 1153.,  711.,  891.,  102.],
       [ 101., 5869.,  752.,  833.,  102.,    0.,    0.,    0.,    0.,
           0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.]],
      dtype=float32)>, <tf.Tensor: shape=(2, 17), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]], dtype=float32)>, <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [0.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>]

```
两者看起来是完全一致的

**Comment by bojone** [comment]
你的意思是换GRU不报错？

**Comment by jerrysjin** [comment]
> 你的意思是换GRU不报错？

对的，如果把模型改成
```python

albert = build_transformer_model(
            config_path = config['model_config_path'],
            checkpoint_path = config['checkpoint_path'],
            model = 'albert',
            return_keras_model = False
            )
        
        output = albert.model.output

        output = Bidirectional(
            GRU(
                units = config['gru_hidden_size'],
                recurrent_dropout = 0.1
                )
            )(output)
        output = Dense(
            units = config['gru_hidden_size'],
            activation = 'relu',
            kernel_initializer = albert.initializer
            )(output)
        output = Dropout(rate = 0.2)(output)
        output = Dense(
            units = config['class_num'],
            activation = 'softmax',
            kernel_initializer = albert.initializer
            )(output)

```

就不会出现上面的报错，可以正常训练

**Comment by jerrysjin** [comment]
> 盲猜没把[CLS] token取出
 
发现了问题，在bert的output后面加了一行，把[CLS][SEP]去掉以后问题就解决了。

 ```python

output = Lambda(lambda x: x[:, 1:-1], name = 'word-token')(output)

```

但有点不明白为什么，[CLS]和[SEP]难道不是跟其他正常token一样也是一个相同维度的向量吗，在代码里有什么特殊的处理吗？

**Comment by jerrysjin** [comment]
似乎是由不同层的参数共享引起的
在尝试打印albert的输入的时候，会出现
```python

AttributeError: Layer Transformer-FeedForward-Norm has multiple inbound nodes, hence the notion of "layer output" is ill-defined. Use `get_output_at(node_index)` instead.

```

参考keras的官方文档，出现原因是因为有参数共享的关系。但至于为什么cnn会出现维度问题，以及为什么bigru就不会出错，还没明白原因。
