### ISSUE TITLE
使用"unilm"参数后模型无法保存成savemodel格式

### ISSUE THREAD

**Issue by phoenixkillerli** [bojone/bert4keras#155]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: tensorflow/tensorflow:2.1.0-gpu-py3
- 你使用的**Python**版本: 3.6.9
- 你使用的**Tensorflow**版本: 2.1.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.7.7
- 你使用纯**keras**还是**tf.keras**:tf.keras
- 你加载的**预训练模型**:albert_tiny

### 核心代码
```python
model = build_transformer_model(
    config_path,
    checkpoint_path,
    model='albert_unshared',
    application='unilm',
    keep_tokens=keep_tokens,  # 只保留keep_tokens中的字，精简原字表
)

output = CrossEntropy(2)(model.inputs + model.outputs)

model = Model(model.inputs, output)
model.compile(optimizer=Adam(1e-5))
model.summary()
```

### 输出信息
训练时有警告信息如下：
```shell
WARNING:tensorflow:5 out of the last 5 calls to <function _make_execution_function.<locals>.distributed_function at 0x7f4f480cdd90> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.
WARNING:tensorflow:6 out of the last 6 calls to <function _make_execution_function.<locals>.distributed_function at 0x7f4f480cdd90> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.
WARNING:tensorflow:7 out of the last 7 calls to <function _make_execution_function.<locals>.distributed_function at 0x7f4f480cdd90> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.
```
保持savemodel代码：
```python
    import tensorflow as tf
    tf.saved_model.save(model, './test')
```
错误信息如下：
```shell
2020-05-22 06:08:35.756816: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
Traceback (most recent call last):
  File "/tf/case_time/train.py", line 142, in <module>
    tf.saved_model.save(model, './test')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/save.py", line 886, in save
    checkpoint_graph_view)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/signature_serialization.py", line 74, in find_function_to_export
    functions = saveable_view.list_functions(saveable_view.root)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/saved_model/save.py", line 142, in list_functions
    self._serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 2420, in _list_functions_for_serialization
    .list_functions_for_serialization(serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/base_serialization.py", line 91, in list_functions_for_serialization
    fns = self.functions_to_serialize(serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 80, in functions_to_serialize
    serialization_cache).functions_to_serialize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 95, in _get_serialized_attributes
    serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/model_serialization.py", line 53, in _get_serialized_attributes_internal
    serialization_cache))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/layer_serialization.py", line 104, in _get_serialized_attributes_internal
    functions = save_impl.wrap_layer_functions(self.obj, serialization_cache)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 172, in wrap_layer_functions
    '{}_layer_call_and_return_conditional_losses'.format(layer.name))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 513, in add_function
    self.add_trace(*self._input_signature)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 429, in add_trace
    trace_with_training(False)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 426, in trace_with_training
    fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 557, in get_concrete_function
    return super(LayerCall, self).get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 919, in get_concrete_function
    concrete = self._stateful_fn.get_concrete_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2434, in get_concrete_function
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 534, in wrapper
    ret = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 113, in wrap_with_training_arg
    lambda: replace_training_and_call(False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/tf_utils.py", line 59, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/smart_cond.py", line 56, in smart_cond
    return false_fn()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 113, in <lambda>
    lambda: replace_training_and_call(False))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/utils.py", line 108, in replace_training_and_call
    return wrapped_call(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/saved_model/save_impl.py", line 576, in call_and_return_conditional_losses
    return layer_call(inputs, *args, **kwargs), layer.get_losses_for(inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 717, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py", line 891, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 807, in __call__
    self._set_mask_metadata(inputs, outputs, input_masks)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1937, in _set_mask_metadata
    output_masks = self.compute_mask(inputs, previous_mask)
  File "/usr/local/lib/python3.6/dist-packages/bert4keras/layers.py", line 235, in compute_mask
    return mask[0]
TypeError: 'NoneType' object is not subscriptable
```
### 自我尝试
升级bert4keras 0.7.3到0.7.7, 升级tensorflow 2.0.0到2.1.0，还是无法正常保存savemodel格式模型。以前没有用"unlim"的分类，提取模型都可以正常保存。这次使用"unlim"进行seq2seq生成任务训练就无法保存。

**Comment by phoenixkillerli** [comment]
继续研究
bert4keras\layers.py
```python
    def compute_mask(self, inputs, mask):
            return mask[0]
```
这里的mask有可能为None, 造成mask[0]抛出异常。
不清楚该如何合理处理，简单加了个判断，运行可以正常保存了。
```python
    def compute_mask(self, inputs, mask):
        if mask:
            return mask[0]
        else:
            return mask
```

**Comment by bojone** [comment]
> 继续研究
> bert4keras\layers.py
> 
> ```python
>     def compute_mask(self, inputs, mask):
>             return mask[0]
> ```
> 
> 这里的mask有可能为None, 造成mask[0]抛出异常。
> 不清楚该如何合理处理，简单加了个判断，运行可以正常保存了。
> 
> ```python
>     def compute_mask(self, inputs, mask):
>         if mask:
>             return mask[0]
>         else:
>             return mask
> ```

谢谢哈，这确实是个bug，我更新下。

**Comment by phoenixkillerli** [comment]
继续问个性能问题，还是这个环境配置，
用原生keras训练比tf.keras要快，我用少量数据做了测试，

类别|1epoch 耗时
-|-
keras|3s
tf.keras|5s

这个现象是否是个例，还是tf.keras实现有问题呢？

**Comment by bojone** [comment]
不是个例。keras快于tf.keras，tf 1.x快于tf 2.x。总之你记住tf越开发越糟糕就是了～
