### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by enningxie** [bojone/bert4keras#16]
> from bert4keras.bert import load_pretrained_model, set_gelu
  File "/home/env/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bert4keras/bert.py", line 4, in <module>
    from .layers import *
  File "/home/env/anaconda3/envs/tensorflow/lib/python3.6/site-packages/bert4keras/layers.py", line 321
    raise Exception, 'Embedding layer not found'

**Comment by captain2017** [comment]
metoo

**Comment by Fan9** [comment]
Traceback (most recent call last):
  File "task_sentiment_albert.py", line 10, in <module>
    from bert4keras.bert import load_pretrained_model, set_gelu
  File "/data/sfang/bert4keras-master/bert4keras/bert.py", line 4, in <module>
    from .layers import *
  File "/data/sfang/bert4keras-master/bert4keras/layers.py", line 321
    raise Exception, 'Embedding layer not found'
                   ^
SyntaxError: invalid syntax
报这里语法错误

**Comment by bojone** [comment]
已修正，烦请再测试一下

**Comment by enningxie** [comment]
> 已修正，烦请再测试一下

🙏
