### ISSUE TITLE
TF.keras加载权重后报错

### ISSUE THREAD

**Issue by Youngyangi** [bojone/bert4keras#166]
### 基本信息
- 你使用的**操作系统**: Win10
- 你使用的**Python**版本: 3.8
- 你使用的**Tensorflow**版本: 2.2.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.7.9
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:Google原版albert_zh

### 核心代码
```python
# 加载预训练模型
bert = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    model='albert',
    return_keras_model=False,
)
output = tf.keras.layers.Dropout(rate=0.1)(bert.model.output)
output = tf.keras.layers.Dense(
    units=2, activation='softmax', kernel_initializer=bert.initializer
)(output)

```

### 输出信息
```shell
Traceback (most recent call last):
  File "D:/Workspace/Doc_cov/Albert/model.py", line 23, in <module>
    output = tf.keras.layers.Dropout(rate=0.1)(bert.model.output)
  File "C:\Users\youngguo\tf\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 953, in __call__
    inputs, outputs = self._set_connectivity_metadata_(
  File "C:\Users\youngguo\tf\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2313, in _set_connectivity_metadata_
    self._add_inbound_node(
  File "C:\Users\youngguo\tf\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2329, in _add_inbound_node
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
  File "C:\Users\youngguo\tf\lib\site-packages\tensorflow\python\util\nest.py", line 617, in map_structure
    structure[0], [func(*x) for x in entries],
  File "C:\Users\youngguo\tf\lib\site-packages\tensorflow\python\util\nest.py", line 617, in <listcomp>
    structure[0], [func(*x) for x in entries],
  File "C:\Users\youngguo\tf\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2329, in <lambda>
    inbound_layers = nest.map_structure(lambda t: t._keras_history.layer,
AttributeError: 'tuple' object has no attribute 'layer'
```

### 自我尝试
验证了是tf.keras的问题，使用普通keras可以跑通。但是模型需要部署tfserving，希望以tf框架运行。

**Comment by Youngyangi** [comment]
设置环境变量后解决了，原来是引入时默认用的keras，没有和后面的tfkeras对齐。
