### ISSUE TITLE
pretraining model使用时无法载入

### ISSUE THREAD

**Issue by mongolia19** [bojone/bert4keras#171]
您好！非常感谢您的开源项目，但在使用中遇到如下问题：

### 基本信息
- 你使用的**操作系统**: centos 服务器 内核 3.10.0-693.el7.x86_64
- 你使用的**Python**版本:  3.6.2
- 你使用的**Tensorflow**版本:  tensorflow-gpu (1.14.0)
- 你使用的**Keras**版本: Keras (2.3.1）
- 你使用的**bert4keras**版本: bert4keras (0.7.7)
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**: chinese_rbtl3_L-3_H-1024_A-16 中文roberta模型

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```
用bert4keras的pretaining.py 文件跑出来的预训练模型，基于我前面提到的模型在我自己语料上做继续训练，整个训练过程没问题。
下面使用这个模型做finetuning出了问题，无法载入继续做预训练的模型到内存。我在使用时把原版roberta的json配置文件和bert_model.ckpt.meta 与vocab.txt都拷贝到了我的自己预训练模型目录下面。还是不成功。
但是 我直接使用下载的roberta模型没问题。
 from bert4keras.models import build_transformer_model as build_bert_model

dir_bert_model = '/data01/bao/bert4keras/pretraining/saved_model'
config_path = os.path.join(dir_bert_model, 'bert_config_rbtl3.json')
checkpoint_path = os.path.join(dir_bert_model, 'bert_model.ckpt')
dict_path = os.path.join(dir_bert_model, 'vocab.txt')

bert_model = build_bert_model(config_path,checkpoint_path,  model='bert')

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
WARNING:tensorflow:From /home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "sentiment_represatation_cls_roberta.py", line 446, in <module>
    bert_model = build_bert_model(config_path,checkpoint_path,  model='bert')
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/bert4keras/models.py", line 1873, in build_transformer_model
    transformer.load_weights_from_checkpoint(checkpoint_path)
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/bert4keras/models.py", line 208, in load_weights_from_checkpoint
    values = [self.load_variable(checkpoint, v) for v in variables]
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/bert4keras/models.py", line 208, in <listcomp>
    values = [self.load_variable(checkpoint, v) for v in variables]
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/bert4keras/models.py", line 513, in load_variable
    variable = super(BERT, self).load_variable(checkpoint, name)
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/bert4keras/models.py", line 186, in load_variable
    return tf.train.load_variable(checkpoint, name)
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/tensorflow_core/python/training/checkpoint_utils.py", line 84, in load_variable
    return reader.get_tensor(name)
  File "/home/kaifa/anaconda3/envs/nl_gpu/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
**tensorflow.python.framework.errors_impl.NotFoundError: Key bert/embeddings/word_embeddings not found in checkpoint**

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
需要用自带的`Transformer`类的`save_weights_as_checkpoint`方法进行权重转换，要不然自带的保存方法，变量名对不上。

**Comment by HUHU69** [comment]
hhhh我今天遇到同样的问题了0.0

**Comment by HUHU69** [comment]
你好，我今天遇到同样的问题了，想请问一下你的转换是训练完成后做的还是训练过程中直接保存正确的checkpoint？
