### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Key bert/encoder/layer_0/attention/self/query/kernel not found in checkpoint

### ISSUE THREAD

**Issue by BrightHai** [bojone/bert4keras#182]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
  macOS 10.14.6
- 你使用的**Python**版本: 
   3.6.5
- 你使用的**Tensorflow**版本: 
   1.13.1
- 你使用的**Keras**版本: 
    2.3.0
- 你使用的**bert4keras**版本: 
   0.8.2
- 你使用纯**keras**还是**tf.keras**: 
   Keras
- 你加载的**预训练模型**:
   albert_tiny_zh_google   https://storage.googleapis.com/albert_zh/albert_tiny_zh_google.zip
### 核心代码
```python
from bert4keras.tokenizers import Tokenizer
from bert4keras.models import build_transformer_model
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


def similarity_count(vec1, vec2, mode='cos'):
    if mode == 'eu':
        return euclidean_distances([vec1,vec2])[0][1]
    if mode == 'cos':
        return cosine_similarity([vec1, vec2])[0][1]


maxlen = 128
config_path = './albert_tiny_zh_google/albert_config_tiny_g.json'
checkpoint_path = './albert_tiny_zh_google/albert_model.ckpt'
dict_path = './albert_tiny_zh_google/vocab.txt'


tokenizer = Tokenizer(dict_path, do_lower_case=True)  # 建立分词器
```

### 输出信息
```shell
Using TensorFlow backend.
WARNING:tensorflow:From /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/albert_zh/predict.py", line 34, in <module>
    model = build_transformer_model(config_path, checkpoint_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert4keras/models.py", line 1935, in build_transformer_model
    transformer.load_weights_from_checkpoint(checkpoint_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert4keras/models.py", line 209, in load_weights_from_checkpoint
    values = [self.load_variable(checkpoint, v) for v in variables]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert4keras/models.py", line 209, in <listcomp>
    values = [self.load_variable(checkpoint, v) for v in variables]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert4keras/models.py", line 516, in load_variable
    variable = super(BERT, self).load_variable(checkpoint, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bert4keras/models.py", line 187, in load_variable
    return tf.train.load_variable(checkpoint, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_utils.py", line 82, in load_variable
    return reader.get_tensor(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 370, in get_tensor
    status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key bert/encoder/layer_0/attention/self/query/kernel not found in checkpoint
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

更换keras和tf版本

**Comment by bojone** [comment]
看上去是没加`model='albert'`

**Comment by BrightHai** [comment]
计算余弦距离的参数形式在sklearn不同版本上有区分
