### ISSUE TITLE
setup.py 文件缺少 bottle 依赖

### ISSUE THREAD

**Issue by BrikerMan** [bojone/bert4keras#203]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Mac OS Big Sur
- 你使用的**Python**版本: 3.8.5
- 你使用的**Tensorflow**版本: 2.3.0
- 你使用的**Keras**版本: NA
- 你使用的**bert4keras**版本: 0.8.5
- 你使用纯**keras**还是**tf.keras**: NA
- 你加载的**预训练模型**: NA

### 核心代码

```python
from bert4keras.models import build_transformer_model
```

### 输出信息

```shell
Using TensorFlow backend.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/brikerman/Desktop/ai/nlp/Kashgari/venv/lib/python3.8/site-packages/bert4keras/models.py", line 6, in <module>
    from bert4keras.snippets import delete_arguments
  File "/Users/brikerman/Desktop/ai/nlp/Kashgari/venv/lib/python3.8/site-packages/bert4keras/snippets.py", line 580, in <module>
    class WebServing(object):
  File "/Users/brikerman/Desktop/ai/nlp/Kashgari/venv/lib/python3.8/site-packages/bert4keras/snippets.py", line 600, in WebServing
    import bottle
ModuleNotFoundError: No module named 'bottle'
```

### 自我尝试

补全依赖就可以解决

```bash
pip install bottle
```

**Comment by bojone** [comment]
了解了，是我编程功底不足了。已经修复哈 https://github.com/bojone/bert4keras/commit/4a4ff37a63708d8fe461423ffa004771ff0c0a36
