### ISSUE TITLE
模型保存后 load_model 报错

### ISSUE THREAD

**Issue by wolaiye1010** [bojone/bert4keras#209]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- 你使用的**Python**版本: 3.7
- 你使用的**Tensorflow**版本: 2.2
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.8.7
- 你使用纯**keras**还是**tf.keras**: 存keras
- 你加载的**预训练模型**:chinese_wwm_ext_L-12_H-768_A-12

### 核心代码
task_seq2seq_autotitle 直接用的这个demo基本没改，训练没有问题，
训练完成后mode.save 保存，然后预测的时候 load_mode()报错

### 输出信息
```shell
=================================================================================================
Total params: 96,488,976
Trainable params: 96,488,976
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "task_seq2seq_autotitle.py", line 269, in <module>
    predictFun()
  File "task_seq2seq_autotitle.py", line 182, in predictFun
    model = load_model("./best_model.h5")
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 583, in load_model
    with H5Dict(filepath, mode='r') as h5dict:
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/io_utils.py", line 191, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
你的错误信息是`Unable to open file`，这跟bert4keras没关系，甚至跟keras都没关系，更像是你读取的文件不是h5文件。请自己检查有无操作上的意外...
