### ISSUE TITLE
model.save问题

### ISSUE THREAD

**Issue by chuzhifeng** [bojone/bert4keras#245]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: 3.65
- 你使用的**Tensorflow**版本: 1.15.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.8.9
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:BERT-BASE

### 核心代码
```
# 模型保存路径
model_dir = "qa_generation_model/"
model.save(model_dir + "{}".format(int(time.time())))
```

### 输出信息
```
Traceback (most recent call last):
  File "qa_generation_s2s.py", line 183, in <module>
    callbacks=[evaluator]
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/training_generator.py", line 260, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/callbacks/callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "qa_generation_s2s.py", line 171, in on_epoch_end
    model.save(model_dir + "{}".format(int(time.time())))
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/network.py", line 1152, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/saving.py", line 449, in save_wrapper
    save_function(obj, filepath, overwrite, *args, **kwargs)
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/saving.py", line 541, in save_model
    _serialize_model(model, h5dict, include_optimizer)
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/saving.py", line 129, in _serialize_model
    model_config['config'] = model.get_config()
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/engine/network.py", line 879, in get_config
    layer_config = layer.get_config()
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/bert4keras/layers.py", line 616, in get_config
    'activation': activations.serialize(self.activation),
  File "/apps/home/rd/anaconda3/envs/MRC/lib/python3.6/site-packages/keras/activations.py", line 200, in serialize
    return activation.__name__
AttributeError: 'list' object has no attribute '__name__'
```

### 自我尝试
当我使用qa_generation_s2s.py代码训练时，修改模型的保存方式是model.save时，出现报错，请问作者，您readme上说支持model.save是这样使用的嘛

**Comment by bojone** [comment]
你是不是用了0.8.9版或者0.9.0版？这两个版本有点问题，我已经在pypi上删掉了，如果你需要save，请用<=0.88或者>=0.9.1版。
