### ISSUE TITLE
nezha模型使用bert of theseus报错

### ISSUE THREAD

**Issue by JaheimLee** [bojone/bert4keras#262]
提问时请尽可能提供如下信息：

### 基本问题
相同测试环境下，bert of theseus代码在加载nezha模型时会出现如下问题，换用roberta模型之后一切正常。

### 输出信息
```shell
Traceback (most recent call last):
  File "sentiment_theseus.py", line 276, in <module>
    theseus_model = bert_of_theseus(predecessor, successor, classfier)
  File "sentiment_theseus.py", line 181, in bert_of_theseus
    model = Model(inputs, outputs)
  File "/data/miniconda3/envs/nvidia-tf/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/nvidia-tf/lib/python3.6/site-packages/keras/engine/network.py", line 94, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/data/miniconda3/envs/nvidia-tf/lib/python3.6/site-packages/keras/engine/network.py", line 241, in _init_graph_network
    self.inputs, self.outputs)
  File "/data/miniconda3/envs/nvidia-tf/lib/python3.6/site-packages/keras/engine/network.py", line 1511, in _map_graph_network
    str(layers_with_complete_input))
ValueError: Graph disconnected: cannot obtain value for tensor Tensor("Successor-Input-Segment:0", shape=(?, ?), dtype=float32) at layer "Successor-Input-Segment". The following previous layers were accessed without issue: ['Predecessor-Input-Segment', 'Predecessor-Input-Token', 'Predecessor-Embedding-Token', 'Predecessor-Embedding-Segment', 'Successor-Embedding-Token', 'Successor-Embedding-Segment', 'Predecessor-Embedding-Token', 'Predecessor-Embedding-Segment', 'Predecessor-Embedding-Token-Segment', 'Successor-Embedding-Token-Segment', 'Predecessor-Embedding-Token-Segment', 'Predecessor-Embedding-Norm', 'Successor-Embedding-Norm', 'Predecessor-Embedding-Norm', 'Predecessor-Embedding-Dropout', 'Predecessor-Embedding-Dropout', 'Successor-Embedding-Dropout', 'Predecessor-Embedding-Relative-Position', 'binary_random_choice_1', 'Predecessor-Transformer-0-MultiHeadSelfAttention', 'Predecessor-Transformer-0-MultiHeadSelfAttention-Dropout', 'Predecessor-Transformer-0-MultiHeadSelfAttention-Add', 'Predecessor-Transformer-0-MultiHeadSelfAttention-Norm', 'Predecessor-Transformer-0-FeedForward', 'Predecessor-Transformer-0-FeedForward-Dropout', 'Predecessor-Transformer-0-FeedForward-Add', 'Predecessor-Transformer-0-FeedForward-Norm', 'Predecessor-Transformer-1-MultiHeadSelfAttention', 'Predecessor-Transformer-1-MultiHeadSelfAttention-Dropout', 'Predecessor-Transformer-1-MultiHeadSelfAttention-Add', 'Predecessor-Transformer-1-MultiHeadSelfAttention-Norm', 'Predecessor-Transformer-1-FeedForward', 'Predecessor-Transformer-1-FeedForward-Dropout', 'Predecessor-Transformer-1-FeedForward-Add', 'Predecessor-Transformer-1-FeedForward-Norm', 'Predecessor-Transformer-2-MultiHeadSelfAttention', 'Predecessor-Transformer-2-MultiHeadSelfAttention-Dropout']
```

### 自我尝试
问题出在创建theseus模型中，应该是embedding或layer在apply时候出的问题，但是还没调试出来。。。

**Comment by bojone** [comment]
是个好问题。我这两天调试调试。

**Comment by bojone** [comment]
找到问题了，插两行就好
```python
def bert_of_theseus(predecessor, successor, classfier):
    """bert of theseus
    """
    inputs = predecessor.inputs
    successor.set_inputs(inputs)  # 新增
    successor.position_bias = None   # 新增
    # 固定住已经训练好的层
    for layer in predecessor.model.layers:
        layer.trainable = False
    classfier.trainable = False
```

**Comment by JaheimLee** [comment]
爆赞！
