### ISSUE TITLE
自定义metric/loss 存在 ValueError: Incompatible shapes: `values` () vs `sample_weight` (None, None)

### ISSUE THREAD

**Issue by redreamality** [bojone/bert4keras#276]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: win10
- 你使用的**Python**版本: 3.7.3
- 你使用的**Tensorflow**版本:  1.14
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.9.6
- 你使用纯**keras**还是**tf.keras**:  keras
- 你加载的**预训练模型**: bert  uncased_L-12_H-768_A-12

### 核心代码
```
def get_f1(y_true, y_pred): #taken from old keras source code
    '''metric'''
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    recall = true_positives / (possible_positives + K.epsilon())
    f1_val = 2*(precision*recall)/(precision+recall+K.epsilon())
    return f1_val

model.compile(optimizer, 
            loss = [binary_crossentropy for i in range(num_pts+num_spans)],             
            loss_weights = [1]*num_pts+[1]*num_spans,
            # metrics=[get_f1]
            )
```

### 输出信息
```
Traceback (most recent call last):
  File "d:/annonimized/main.py", line 322, in <module>
    metrics=[get_f1]
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\engine\training.py", line 222, in compile
    masks=masks)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\engine\training.py", line 871, in _handle_metrics
    self._per_output_metrics[i], target, output, output_mask)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\engine\training.py", line 842, in _handle_per_output_metrics
    metric_fn, y_true, y_pred, weights=weights, mask=mask)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\engine\training_utils.py", line 1033, in call_metric_function
    update_ops = metric_fn.update_state(y_true, y_pred, sample_weight=weights)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\utils\metrics_utils.py", line 42, in decorated
    update_op = update_state_fn(*args, **kwargs)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\metrics.py", line 320, in update_state
    matches, sample_weight=sample_weight)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\metrics.py", line 181, in update_state
    sample_weight = losses_utils.broadcast_weights(values, sample_weight)
  File "C:\Users\annonimized\Anaconda3\lib\site-packages\keras\utils\losses_utils.py", line 113, in broadcast_weights
values_shape, weights_shape))
ValueError: Incompatible shapes: `values` () vs `sample_weight` (None, None)
```

### 自我尝试
基本可以确定是这段代码与bert4keras组合的问题，已经交叉验证:
这段代码+transformers包  ok
这段代码+裸LSTM ok
这段代码+bert4keras  fail
metrics=[‘accuracy’]+bert4keras  ok

另外 自定义loss也有类似问题

**Comment by bojone** [comment]
模型的搭建部分代码可以发一下吗？目前看不出什么问题。最好简化一下，提供一个可复现的代码，谢谢反馈。

**Comment by llango** [comment]
我也出现同样的问题， 还在找原因

**Comment by ZeroE04** [comment]
也出现这个问题

**Comment by bojone** [comment]
试试在模型的最后输出接个Lambda层：
```python
output = Lambda(lambda x: x)(output)
```

**Comment by AngelaSunny** [comment]
same problem
## 配置：系统Linux
python==3.7.10
tensorflow-gpu=1.15.0
keras=2.3.1
bert4keras==0.10.6
## 模型搭建
![image](https://user-images.githubusercontent.com/6916989/127840485-6afcfbb3-1b8a-4cba-8314-042eeaf5d007.png)

## 模型编译：
![image](https://user-images.githubusercontent.com/6916989/127839770-d484d585-367b-4501-87b8-f554d8177698.png)

## loss报错
File "/nlp/py3tf1.15/lib/python3.7/site-packages/keras/utils/losses_utils.py", line 113, in broadcast_weights
    values_shape, weights_shape))
ValueError: Incompatible shapes: `values` () vs `sample_weight` (None, None)

**Comment by AngelaSunny** [comment]
> same problem
> 
> ## 配置：系统Linux
> python==3.7.10
> tensorflow-gpu=1.15.0
> keras=2.3.1
> bert4keras==0.10.6
> 
> ## 模型搭建
> ![image](https://user-images.githubusercontent.com/6916989/127840485-6afcfbb3-1b8a-4cba-8314-042eeaf5d007.png)
> 
> ## 模型编译：
> ![image](https://user-images.githubusercontent.com/6916989/127839770-d484d585-367b-4501-87b8-f554d8177698.png)
> 
> ## loss报错
> File "/nlp/py3tf1.15/lib/python3.7/site-packages/keras/utils/losses_utils.py", line 113, in broadcast_weights
> values_shape, weights_shape))
> ValueError: Incompatible shapes: `values` () vs `sample_weight` (None, None)

--在cpu上训练是可以的
