### ISSUE TITLE
使用ernie模型训练问题

### ISSUE THREAD

**Issue by yzq170320** [bojone/bert4keras#281]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: linux 
- 你使用的**Python**版本: python3.7
- 你使用的**Tensorflow**版本: 1.14
- 你使用的**Keras**版本: 2.2.5
- 你使用的**bert4keras**版本: 0.4.3
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:ernie

### 核心代码
```python

def build_model(mode='bert', filename='bert', lastfour=False, LR=1e-5, DR=0.2):

    path = 'D:/work_project/TinyBert-master/epidemic-sentence-pair-master/epidemic-sentence-pair-master/data/External/'+filename+'/'
    config_path = path+'bert_config.json'
    checkpoint_path = path+'bert_model.ckpt'
    #checkpoint_path = tf.train.latest_checkpoint(path)
    print("mode:%s,path:%s"%(mode,checkpoint_path))
    dict_path = path+'vocab.txt'

    global tokenizer
    tokenizer = Tokenizer(dict_path, do_lower_case=True)

    bert = build_transformer_model(
        config_path=config_path,
        checkpoint_path=checkpoint_path,
        with_pool=True,
        model=mode,
        return_keras_model=False,
    )

model = build_model(mode='bert',filename='ernie',lastfour=False)
do_train(mode='bert',filename='ernie',lastfour=False,LR=1e-5)
do_train(mode='bert',filename='ernie',lastfour=False,LR=1e-5,ext=True)

# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```
Traceback (most recent call last):
  File "D:/work_project/TinyBert-master/epidemic-sentence-pair-master/epidemic-sentence-pair-master/code/train.py", line 224, in <module>
    model = build_model(mode='bert',filename='ernie',lastfour=False)
  File "D:/work_project/TinyBert-master/epidemic-sentence-pair-master/epidemic-sentence-pair-master/code/train.py", line 47, in build_model
    bert = build_transformer_model(
  File "D:\work_soft\Python3\lib\site-packages\bert4keras\models.py", line 2290, in build_transformer_model
    transformer = MODEL(**configs)
  File "D:\work_soft\Python3\lib\site-packages\bert4keras\models.py", line 371, in __init__
    super(BERT, self).__init__(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'intermediate_size'
### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
使用的是https://github.com/ArthurRizar/tensorflow_ernie方法将模型转换为tf模型；
曾在python3.8环境和bert4keras=0.9.3进行模型训练。bert和roberta模型可以训练，ernie转化后的模型报错

**Comment by yzq170320** [comment]
自己在config中补上数据
