### ISSUE TITLE
修改task_seq2seq_autotitle.py在多GPU环境下微调时遇到的问题

### ISSUE THREAD

**Issue by pcibusgood** [bojone/bert4keras#286]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Ubuntu 18.04
- 你使用的**Python**版本: 3.7.0
- 你使用的**Tensorflow**版本: 1.15
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.9.7
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:chinese_wwm_ext_L-12_H-768_A-12

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。

# 主机上的4个K80核心均启用
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "4,3,1,0"

# 把原来代码中建立模型的部分放在一个build_model函数中
def build_model():
    model = build_transformer_model(
        config_path,
        checkpoint_path,
        application='unilm',
        keep_tokens=keep_tokens,  # 只保留keep_tokens中的字，精简原字表
    )

    output = CrossEntropy(2)(model.inputs + model.outputs)

    model = Model(model.inputs, output)
    model.compile(optimizer=Adam(1e-5))
    model.summary()
    return model

# 在main函数中通过MirroredStrategy方法调用build_model函数
if __name__ == '__main__':
    evaluator = Evaluator()
    train_generator = data_generator(txts, batch_size)

    strategy = tf.distribute.MirroredStrategy()
    with strategy.scope():
        model = build_model()

    model.fit(
        train_generator.forfit(),
        steps_per_epoch=steps_per_epoch,
        epochs=epochs,
        callbacks=[evaluator]
    )
else:
    model.load_weights('./best_model.weights')

```

### 输出信息
```shell
# 请在此处贴上你的调试输出
# 在设置 TF_KERAS=1 时，输出如下错误信息：
Total params: 96,488,976
Trainable params: 96,488,976
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "task_seq2seq_autotitle_new_mgpu1.py", line 163, in <module>
    callbacks=[evaluator]
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 619, in fit
    epochs=epochs)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 2314, in _distribution_standardize_user_data
    assert isinstance(x, dataset_ops.DatasetV2)
AssertionError
(tensorflow) maqy@maqy-Z9PE-D8:~/EXAM_TF/bert4keras/bert4keras-master$ 



# 在设置 TF_KERAS=0 时，输出如下错误信息：
Total params: 96,488,976
Trainable params: 96,488,976
Non-trainable params: 0
__________________________________________________________________________________________________
WARNING:tensorflow:From /home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Traceback (most recent call last):
  File "task_seq2seq_autotitle_new_mgpu1.py", line 163, in <module>
    callbacks=[evaluator]
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training.py", line 1147, in fit
    initial_epoch=initial_epoch)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training_generator.py", line 42, in fit_generator
    model._make_train_function()
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/engine/training.py", line 316, in _make_train_function
    loss=self.total_loss)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/keras/optimizers.py", line 550, in get_updates
    if getattr(p, 'constraint', None) is not None:
  File "/home/maqy/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/ops/variables.py", line 568, in constraint
    raise NotImplementedError
NotImplementedError
(tensorflow) maqy@maqy-Z9PE-D8:~/EXAM_TF/bert4keras/bert4keras-master$ 
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
测试过其它在当前软硬件环境下使用4个K80核心通过mirroedstrategy策略进行mnist训练的代码，可以正常在多个GPU上同时进行正常训练。
删除主函数中启用多GPU环境的两行代码后，程序可以正常执行了，感觉这个问题还是与多GPU策略有关。
分别设置 TF_KERAS=1 和 TF_KERAS=0 时的情况，均不能正常开始微调过程，但是模型在各个GPU上应该已经加载上了。

**Comment by bojone** [comment]
设置环境变量要放在脚本的最开头，bert4keras导入之前。

**Comment by pcibusgood** [comment]
是的，是在命令行先设置的export TF_KERAS=1，然后通过python运行的这个程序

**Comment by bojone** [comment]
我试了下，启用多GPU还要多修改一下，要模仿 https://github.com/bojone/bert4keras/blob/master/pretraining/pretraining.py 里边的写法才行。

**Comment by pcibusgood** [comment]
把TF版本升级为2.2.0之后，多GPU已经能正常进行“微调”了。

**Comment by pcibusgood** [comment]
运行过程中会出现如下WARNING信息：

WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f9603b7ce60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

**Comment by pcibusgood** [comment]
关于task_seq2seq_autotitle.py在多GPU环境下运行的问题，能确定是TensorFlow版本不同引起的；
根据我测试的情况，在TensorFlow 1.15版本时，使用mirroedstrategy策略进行多GPU的“微调”时，是无法正常运行的；
但是相同的代码在TensorFlow 2.2.0版本环境下，能使用所有配置的GPU进行finetune。
最后的这项WARNING信息，也是与TF版本相关，在TF 2.2.0时有这个WARNING提示，记得在TF 1.15.0环境下是没有这个WARNING提示信息的。
所以关闭此issue。
