### ISSUE TITLE
包含bert的Model无法应用到TimeDDistributed中

### ISSUE THREAD

**Issue by phoenixkillerli** [bojone/bert4keras#3]
## 测试代码如下
```python

from bert4keras.bert import load_pretrained_model as load_trained_model_from_checkpoint
from bert4keras.utils import SimpleTokenizer as Tokenizer
from keras.layers import Input, TimeDistributed
from keras.models import Model


config_path = './chinese_L-12_H-768_A-12/bert_config.json'
checkpoint_path = './chinese_L-12_H-768_A-12/bert_model.ckpt'
dict_path = './chinese_L-12_H-768_A-12/vocab.txt'

bert_model = load_trained_model_from_checkpoint(config_path,
                                                checkpoint_path)

for l in bert_model.layers:
    l.trainable = True

MAX_SENTENCE_LENGTH = 128
MAX_SENTENCE_COUNT = 64


x1_in = Input(shape=(MAX_SENTENCE_LENGTH, ), dtype='int32')
x2_in = Input(shape=(MAX_SENTENCE_LENGTH, ), dtype='int32')

x1, x2 = x1_in, x2_in
sentence = bert_model([x1, x2])

# sentence = Lambda(lambda x: x[:, 0])(sentence)
model1 = Model([x1_in, x2_in], sentence)
model1.summary()

texts_in = Input(shape=(MAX_SENTENCE_COUNT, MAX_SENTENCE_LENGTH, 2),
                 dtype='int32')
attention_weighted_sentences = TimeDistributed(model1)(texts_in)
model = Model(texts_in, attention_weighted_sentences)
model.summary()

```
## 报错
```python
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "/home/phoenixkiller/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/phoenixkiller/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/phoenixkiller/.vscode/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/phoenixkiller/anaconda3/envs/keras_debug/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/phoenixkiller/anaconda3/envs/keras_debug/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/phoenixkiller/anaconda3/envs/keras_debug/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/phoenixkiller/source/bert4keras/test copy.py", line 36, in <module>
    attention_weighted_sentences = TimeDistributed(model1)(texts_in)
  File "/home/phoenixkiller/source/keras/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/phoenixkiller/source/keras/keras/layers/wrappers.py", line 248, in call
    y = self.layer.call(inputs, **kwargs)
  File "/home/phoenixkiller/source/keras/keras/engine/network.py", line 564, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "/home/phoenixkiller/source/keras/keras/engine/network.py", line 798, in run_internal_graph
    assert str(id(x)) in tensor_map, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("model_1/Encoder-12-FeedForward-Norm/add_1:0", shape=(?, 128, 768), dtype=float32)

```

**Comment by bojone** [comment]
我没见过这样用的，难道你用别的模型成功过么？

**Comment by phoenixkillerli** [comment]
## 这个代码可以跑通
```python
import keras
from keras.models import *
from keras.layers import *
from keras.optimizers import *
from keras.callbacks import *
from keras import regularizers
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras import backend as K
from keras.utils import CustomObjectScope
from keras.engine.topology import Layer
from keras import initializers

TOKENIZER_STATE_PATH = 'saved_models/tokenizer.p'
GLOVE_EMBEDDING_PATH = 'saved_models/glove.6B.100d.txt'


class Attention(Layer):
    def __init__(self, regularizer=None, **kwargs):
        super(Attention, self).__init__(**kwargs)
        self.regularizer = regularizer
        self.supports_masking = True

    def build(self, input_shape):
        # Create a trainable weight variable for this layer.
        self.context = self.add_weight(name='context',
                                       shape=(input_shape[-1], 1),
                                       initializer=initializers.RandomNormal(
                                           mean=0.0, stddev=0.05, seed=None),
                                       regularizer=self.regularizer,
                                       trainable=True)
        super(Attention, self).build(input_shape)

    def call(self, x, mask=None):
        attention_in = K.exp(K.squeeze(K.dot(x, self.context), axis=-1))
        attention = attention_in / K.expand_dims(K.sum(attention_in, axis=-1),
                                                 -1)

        if mask is not None:
            # use only the inputs specified by the mask
            # import pdb; pdb.set_trace()
            attention = attention * K.cast(mask, 'float32')

        weighted_sum = K.batch_dot(K.permute_dimensions(x, [0, 2, 1]),
                                   attention)
        return weighted_sum

    def compute_output_shape(self, input_shape):
        print(input_shape)
        return (input_shape[0], input_shape[-1])


class HNATT():
    def __init__(self):
        self.model = None
        self.MAX_SENTENCE_LENGTH = 100
        self.MAX_SENTENCE_COUNT = 100
        self.VOCABULARY_SIZE = 10000
        self.word_embedding = None
        self.model = None
        self.word_attention_model = None
        self.tokenizer = None
        self.class_count = 2

    def _build_model(self,
                     n_classes=2,
                     embedding_dim=100,
                     embeddings_path=False):
        l2_reg = regularizers.l2(1e-8)
        sentence_in = Input(shape=(self.MAX_SENTENCE_LENGTH, ), dtype='int32')
        embedded_word_seq = Embedding(
            self.VOCABULARY_SIZE,
            embedding_dim,
            name='word_embeddings',
        )(sentence_in)
        word_encoder = Bidirectional(
            GRU(50, return_sequences=True,
                kernel_regularizer=l2_reg))(embedded_word_seq)
        dense_transform_w = Dense(100,
                                  activation='relu',
                                  name='dense_transform_w',
                                  kernel_regularizer=l2_reg)(word_encoder)
        attention_weighted_sentence = Model(
            sentence_in,
            Attention(name='word_attention',
                      regularizer=l2_reg)(dense_transform_w))
        self.word_attention_model = attention_weighted_sentence
        attention_weighted_sentence.summary()

        # Generate sentence-attention-weighted document scores
        texts_in = Input(shape=(self.MAX_SENTENCE_COUNT,
                                self.MAX_SENTENCE_LENGTH),
                         dtype='int32')
        attention_weighted_sentences = TimeDistributed(
            attention_weighted_sentence)(texts_in)
        sentence_encoder = Bidirectional(
            GRU(50, return_sequences=True,
                kernel_regularizer=l2_reg))(attention_weighted_sentences)
        dense_transform_s = Dense(100,
                                  activation='relu',
                                  name='dense_transform_s',
                                  kernel_regularizer=l2_reg)(sentence_encoder)
        attention_weighted_text = Attention(
            name='sentence_attention', regularizer=l2_reg)(dense_transform_s)
        prediction = Dense(n_classes,
                           activation='softmax')(attention_weighted_text)
        model = Model(texts_in, prediction)
        model.summary()

        model.compile(  #optimizer=RMSprop(lr=0.001, rho=0.9, epsilon=None, decay=0.0),
            #optimizer=SGD(lr=0.01, decay=1e-6, nesterov=True),
            optimizer=Adam(lr=0.001),
            loss='categorical_crossentropy',
            metrics=['acc'])

        return model

h = HNATT()
h._build_model()
```

**Comment by bojone** [comment]
那是我孤陋寡闻了。按道理来说你应该要传入两个(MAX_SENTENCE_COUNT, MAX_SENTENCE_LENGTH)大小的输入，而不是一个(MAX_SENTENCE_COUNT, MAX_SENTENCE_LENGTH, 2)的输入吧？

**Comment by phoenixkillerli** [comment]
谢谢指点

**Comment by Faysir** [comment]
> 谢谢指点

这个问题最后的解决方案是什么？

**Comment by ConnollyLeon** [comment]
这个问题我现在也遇到了，Timedistributed要求每一层都提供compute_output_shape的实现，而苏大佬的FeedForward层里面没有实现这一块，所以在运行的时候会报错，建议苏大佬可以帮忙把每一层的computer_output_shape的实现给加上，来帮助解决这一个问题。
