### ISSUE TITLE
models类 apply 函数不支持sparse_inputs

### ISSUE THREAD

**Issue by Atakey** [bojone/bert4keras#308]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: 
- win10
- 你使用的**Python**版本: 
- 3.6.10
- 你使用的**Tensorflow**版本: 
- 1.15.0
- 你使用的**Keras**版本: 
- 2.2.4
- 你使用的**bert4keras**版本: 
- 0.10.3
- 你使用纯**keras**还是**tf.keras**: 
- 纯 bert4keras
- 你加载的**预训练模型**:
- 原始bert预训练模型

### 核心代码
```
import json
import os
from pathlib import Path

from bert4keras.models import BERT, Input, Model
from bert4keras.optimizers import Adam


class Sparse_Test_BERT(BERT):
    def get_inputs(self):
        test_input = self.apply(
            layer=Input,
            batch_shape=(None, None),
            sparse=True,
            name='Sparse_Test_Input',
        )
        inputs = super().get_inputs()
        inputs.append(test_input)
        return inputs


if __name__ == '__main__':
  config_path =  'data_path/model/bert_model/bert_model/bert_config.json'
  checkpoint_path ='data_path/model/bert_model/bert_model/bert_model.ckpt'
  dict_path = 'data_path/model/bert_model/bert_model/vocab.txt'
  configs = {'config_path': config_path, 'checkpoint_path': checkpoint_path,
             'return_keras_model': True, 'max_position': 512, 'dropout_rate': 0.1,
             'segment_vocab_size': 2
             }
  configs.update(json.load(open(config_path)))
  transformer = Sparse_Test_BERT(**configs)
  transformer.build(**configs)
  model = transformer.model
  test_model = Model(model.input, model.output)
  model.compile(
      loss=lambda y_true, y_pred: model.output,
      optimizer=Adam(5e-5),
  )
```

### 输出信息
```shell
Traceback (most recent call last):
  File "...test/sparse_test.py", line 47, in <module>
    transformer.build(**configs)
  File "...\site-packages\bert4keras\models.py", line 83, in build
    inputs = self.get_inputs()
  File ".../sparse_test.py", line 27, in get_inputs
    name='Sparse_Test_Input',
  File "...\bert4keras\models.py", line 135, in apply
    name = layer.name
AttributeError: 'SparseTensor' object has no attribute 'name'
```

### 自我尝试
bert4keras/models.py:134
```
if name not in self.layers:
    layer = layer(**kwargs)
    name = layer.name
    self.layers[name] = layer
```
增加如下代码：
```
if name not in self.layers:
    layer = layer(**kwargs)
    if hasattr(layer, 'name'):
        name = layer.name
    self.layers[name] = layer
```
解决

**Comment by bojone** [comment]
哈哈，奇怪的需求增加了～这个sparse输入有什么场景吗？

**Comment by Atakey** [comment]
> 哈哈，奇怪的需求增加了～这个sparse输入有什么场景吗？
魔改哈哈哈，增加复杂的东西嵌入用于final_layers

**Comment by bojone** [comment]
OK，我自己也测测看，抽空把它整合进去。

**Comment by Atakey** [comment]
> OK，我自己也测测看，抽空把它整合进去。
