### ISSUE TITLE
NER任务报错：ValueError: Asked to get output at node 11, but the layer has only 4 inbound nodes.

### ISSUE THREAD

**Issue by chros425** [bojone/bert4keras#350]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  centos7.8
- 你使用的**Python**版本: 3.6.4
- 你使用的**Tensorflow**版本: 2.2.0
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.6
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**: albert_tiny_google_zh_489k

### 核心代码
```python
# 请在此处贴上你的核心代码。
# 请尽量只保留关键部分，不要无脑贴全部代码。

# 使用albert
model = build_transformer_model(
    config_path,
    checkpoint_path,
    model='albert',
)
output_layer = 'Transformer-FeedForward-Norm'
output = model.get_layer(output_layer).get_output_at(bert_layers - 1)

output = Dense(len(categories) * 2 + 1)(output)
CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
output = CRF(output)

model = Model(model.input, output)
model.summary()

model.compile(
    loss=CRF.sparse_loss,
    optimizer=Adam(learning_rate),
    metrics=[CRF.sparse_accuracy]
)
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
2021-05-28 01:01:43.731024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0, 1
2021-05-28 01:01:43.731080: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2021-05-28 01:01:43.736168: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-28 01:01:43.736197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 1 
2021-05-28 01:01:43.736216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N Y 
2021-05-28 01:01:43.736246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 1:   Y N 
2021-05-28 01:01:43.741663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1159 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
2021-05-28 01:01:43.744775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 29945 MB memory) -> physical GPU (device: 1, name: Tesla V100-PCIE-32GB, pci bus id: 0000:d8:00.0, compute capability: 7.0)
Traceback (most recent call last):
  File "task_ner_crf_albert.py", line 136, in <module>
    output = model.get_layer(output_layer).get_output_at(bert_layers - 1)
  File "/opt/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1790, in get_output_at
    'output')
  File "/opt/chh/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2387, in _get_node_attribute_at_index
    str(len(self._inbound_nodes)) + ' inbound nodes.')
ValueError: Asked to get output at node 11, but the layer has only 4 inbound nodes.
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
看到之前issue中有人问过同样的问题，不过没有给出解决方案就关闭了

**Comment by bojone** [comment]
动动脑好吗？理解一下代码好吗？albert tiny只有4层，为什么bert_layers还要设为12？

**Comment by chros425** [comment]
> 动动脑好吗？理解一下代码好吗？albert tiny只有4层，为什么bert_layers还要设为12？

好的，谢谢大佬
