### ISSUE TITLE
多分类改为多标签分类遇到的问题

### ISSUE THREAD

**Issue by Veyronl** [bojone/bert4keras#413]
提问时请尽可能提供如下信息：
苏神，先忽略，我再排查一下

### 基本信息
- 你使用的**操作系统**: linux
- 你使用的**Python**版本: python==3.6
- 你使用的**Tensorflow**版本: 1.14.0
- 你使用的**Keras**版本: 2.3.0
- 你使用的**bert4keras**版本: 0.10.8
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**:bert

### 核心代码
def load_data(filename):
    """加载数据
    单条格式：(文本, 标签id)
    """
    df_data = pd.read_csv(filename)
    # df_data['data'] = df_data.apply(lambda x: (x['content'], int(x['tag'])), axis=1)
    # D = df_data['data'].tolist()

    D = []
    for row in df_data.itertuples():
        y_label = [0] * num_classes
        y_label[int(getattr(row, 'tag'))] = 1
        D.append((getattr(row, 'content'), y_label))
    return D

bert = build_transformer_model(
    config_path=config_path,
    checkpoint_path=checkpoint_path,
    model='bert',
    return_keras_model=False,
)

output = Lambda(lambda x: x[:, 0], name='CLS-token')(bert.model.output)
output = Dense(
    units=num_classes,
    activation='sigmoid',
    kernel_initializer=bert.initializer
)(output)

model = keras.models.Model(bert.model.input, output)
model.summary()

model.compile(
    loss='binary_crossentropy',
    optimizer=Adam(1e-5),  # 用足够小的学习率
    metrics=['binary_accuracy'],
)

```

### 输出信息
Epoch 1/10
Traceback (most recent call last):
  File "multi_brand_name.py", line 146, in <module>
    train()
  File "multi_brand_name.py", line 141, in train
    callbacks=[evaluator]
  File "/home/ops/miniconda3/envs/weilong/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 673, in fit
    initial_epoch=initial_epoch)
  File "/home/ops/miniconda3/envs/weilong/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/ops/miniconda3/envs/weilong/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/ops/miniconda3/envs/weilong/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1153, in train_on_batch
    extract_tensors_from_dataset=True)
  File "/home/ops/miniconda3/envs/weilong/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2692, in _standardize_user_data
    y, self._feed_loss_fns, feed_output_shapes)
  File "/home/ops/miniconda3/envs/weilong/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_utils.py",line 549, in check_loss_and_target_compatibility
    ' while using as loss `' + loss_name + '`. '
ValueError: A target array with shape (16, 1, 4516) was passed for an output of shape (None, 4516) while using as loss `binary_crossentropy`. This loss expects targets to have the same shape as the output.
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
使用多分类是正常的，修改了loss，对输入label进行one hot。显示输出的shape是对的，要对齐的target shape不对
Evaluator这部分目前没改

**Comment by bojone** [comment]
目测是data_generator的`[label]`改为`label`就行了

**Comment by Veyronl** [comment]
谢谢苏神，已解决
