### ISSUE TITLE
[BUG] add_cls and add_sep are not defined in BasicTokenizer

### ISSUE THREAD

**Issue by ziwenhan** [bojone/bert4keras#43]
There exists a problem about `Tokenizer`, which not defines the `add_cls` and `add_sep`.

> Traceback (most recent call last):
  File "albert.py", line 156, in <module>
    callbacks=[evaluator])
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/keras/engine/training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/keras/utils/data_utils.py", line 742, in get
    six.reraise(*sys.exc_info())
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/keras/utils/data_utils.py", line 711, in get
    inputs = future.get(timeout=30)
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/keras/utils/data_utils.py", line 650, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "albert.py", line 93, in forfit
    for d in self.__iter__(True):
  File "albert.py", line 81, in __iter__
    token_ids, segment_ids = tokenizer.encode(text1, text2, max_length=MAX_LEN)
  File "/home/songuser/anaconda3/envs/keras/lib/python3.7/site-packages/bert4keras/tokenizer.py", line 83, in encode
    delta_1 = int(add_cls) + int(add_sep)

```
def encode(self,
               first_text,
               second_text=None,
               max_length=None,
               first_length=None,
               second_length=None):
        """输出文本对应token id和segment id
        如果传入first_length，则强行padding第一个句子到指定长度；
        同理，如果传入second_length，则强行padding第二个句子到指定长度。
        """
        first_tokens = self.tokenize(first_text, add_cls=False, add_sep=False)
        delta_1 = int(add_cls) + int(add_sep)   # add_cls and add_sep are not defined
        delta_2 = int(add_cls) + int(add_sep) * 2
        if second_text is None:
            if max_length is not None:
                first_tokens = first_tokens[:max_length - delta_1]
```

**Comment by bojone** [comment]
I am sorry for it and it has been fixed 30 minutes ago
