### ISSUE TITLE
NER任务例子中，在尝试添加CNN层时，提示CRF层中reshape维度错误，请大佬帮忙看看

### ISSUE THREAD

**Issue by timetrave1** [bojone/bert4keras#460]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: win10
- 你使用的**Python**版本: 3.5
- 你使用的**Tensorflow**版本:1.15 
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本:0.11.1 
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**:bert

### 核心代码
```python
model = build_transformer_model(
    config_path,
    checkpoint_path,
)
output_layer = 'Transformer-%s-FeedForward-Norm' % (bert_layers - 1)
bert_output = model.get_layer(output_layer).output

# 修改部分
token_embedding = Lambda(lambda x: x[:, 1:-1], name='token')(bert_output)
cnn1 = Conv1D(filters=64,kernel_size=3,padding='same',activation='relu',dilation_rate=1)(token_embedding)
cnn2 = Conv1D(filters=128,kernel_size=3,padding='same',activation='relu',dilation_rate=1)(cnn1)
cnn3 = Conv1D(filters=128,kernel_size=3,padding='same',activation='relu',dilation_rate=2)(cnn2)
output = Dense(len(categories) * 2 + 1)(cnn3)

CRF = ConditionalRandomField(lr_multiplier=crf_lr_multiplier)
output = CRF(output)

model = Model(model.input, output)
model.summary()

model.compile(
    loss=CRF.sparse_loss,
    optimizer=Adam(learning_rate),
    metrics=[CRF.sparse_accuracy]
)
```

### 输出信息
```shell
Traceback (most recent call last):
  File "run_train_cnn_crf.py", line 222, in <module>
    callbacks=[evaluator]
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/bert4keras/layers.py", line 80, in fit
    return self.fit_generator(x, *args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/root/miniconda3/envs/myconda/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 4096 values, but the requested shape has 4032
         [[{{node loss/conditional_random_field_1_loss/Reshape}}]]
         [[{{node loss/mul}}]]
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。
尝试了各类修改方法，百思不得其解，不知道CRF中的维度如何出现问题

**Comment by Thove** [comment]
非常急切地需要您的帮助：我遇到了同样的问题报错简直一模一样

**Comment by Thove** [comment]
我的报错信息最后一行，后一个数字总是比前一个少32，刚好是一个bacth的长度

**Comment by timetrave1** [comment]
尝试使用从bert4keras中导入的keras试试
