### ISSUE TITLE
from bert4keras.backend import keras, K

### ISSUE THREAD

**Issue by LaniakeaS** [bojone/bert4keras#503]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**: Windows11
- 你使用的**Python**版本: 3.7.16
- 你使用的**Tensorflow**版本: 1.15
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.10.0
- 你使用纯**keras**还是**tf.keras**: tf.keras
- 你加载的**预训练模型**: T5 PEGASUS

### 核心代码
```python
from bert4keras.backend import keras, K
```

### 输出信息
```shell
2023-02-14 13:34:08.691515: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2023-02-14 13:34:08.691732: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\73161\Documents\文档审核\t5-pegasus\finetune.py", line 9, in <module>
    from bert4keras.backend import keras, K
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\bert4keras\backend.py", line 8, in <module>
    import tensorflow as tf
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\core\framework\graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\core\framework\node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\tensorflow_core\core\framework\tensor_shape_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "C:\Users\73161\anaconda3\envs\t5-pegasus\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

进程已结束,退出代码1

```

### 自我尝试
完全看不懂这个报错说明了什么问题。开头说了gpu动态库无法找到，但貌似和后面的报错没有关系。

**Comment by FankLi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LaniakeaS** [comment]
Downgrade the protobuf package to 3.20.x or lower.
