### ISSUE TITLE
model.save() 保存模型时

### ISSUE THREAD

**Issue by dashilu1573** [bojone/bert4keras#507]
model.save() 保存SavedModel时，报错：

Traceback (most recent call last):
  File "/Users/luyafei/Downloads/code/DeepTextMatch/SBERT/run.py", line 142, in <module>
    model.fit(train_generator.forfit(),
  File "/Users/luyafei/opt/anaconda3/envs/py3-tf2-new/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/luyafei/opt/anaconda3/envs/py3-tf2-new/lib/python3.9/site-packages/keras/layers/serialization.py", line 117, in populate_deserializable_objects
    LOCAL.ALL_OBJECTS['Functional'] = models.Functional
AttributeError: module 'keras.api._v2.keras.models' has no attribute 'Functional'

提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**操作系统**:  mac linux下都尝试不行
- 你使用的**Python**版本:  3.9
- 你使用的**Tensorflow**版本:  tf2.9.0
- 你使用的**Keras**版本:  2.9.0
- 你使用的**bert4keras**版本: 
- 你使用纯**keras**还是**tf.keras**:  tf.keras
- 你加载的**预训练模型**:  chinese_wwm_ext_L-12_H-768_A-12

### 核心代码
```python

        # 6. model fit
        model.fit(train_generator.forfit(),
                  steps_per_epoch=len(train_generator),
                  epochs=epochs,
                  callbacks=[earlystop, checkpoint])

        model.save("../output/savedmodel/")  # SavedModel 格式
```

### 输出信息
```shell
# 请在此处贴上你的调试输出
```

### 自我尝试
不管什么问题，请先尝试自行解决，“万般努力”之下仍然无法解决再来提问。此处请贴上你的努力过程。

**Comment by bojone** [comment]
这么新的tf和keras我无能为力啊，抱歉。
