### ISSUE TITLE
4080显卡适配问题，failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by lancelotleod** [bojone/bert4keras#508]
提问时请尽可能提供如下信息：

### 基本信息
- 你使用的**显卡**: rtx4080
- 你使用的**操作系统**: win11
- 你使用的**Python**版本: python3.7.16
- 你使用的**Tensorflow**版本: 1.14
- 你使用的**Keras**版本: 2.3.1
- 你使用的**bert4keras**版本: 0.11.4
- 你使用纯**keras**还是**tf.keras**: keras
- 你加载的**预训练模型**:chinese_wwm_L-12_H-768_A-12

### 核心代码
```python
与bert4keras/examples/task_seq2seq_autotitle.py
中保持一致
```

### 输出信息
```shell
WARNING:tensorflow:From D:\anaconda\envs\py37tf14gpu\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

2023-03-02 15:32:19.571120: E tensorflow/stream_executor/cuda/cuda_blas.cc:428] failed to run cuBLAS routine: CUBLAS_STATUS_EXECUTION_FAILED
2023-03-02 15:32:19.571196: E tensorflow/stream_executor/cuda/cuda_blas.cc:2301] Internal: failed BLAS call, see log for details
Traceback (most recent call last):
  File "D:\PycharmProjects\bert\test.py", line 186, in <module>
    out1=autotitle.generate(datas[i])
  File "D:\PycharmProjects\bert\test.py", line 113, in generate
    topk=topk)  # 基于beam search
  File "D:\anaconda\envs\py37tf14gpu\lib\site-packages\bert4keras\snippets.py", line 605, in beam_search
    inputs, output_ids, states, temperature, 'logits'
  File "D:\anaconda\envs\py37tf14gpu\lib\site-packages\bert4keras\snippets.py", line 552, in new_predict
    prediction = predict(self, inputs, output_ids, states)
  File "D:\PycharmProjects\bert\test.py", line 107, in predict
    return self.last_token(model).predict([token_ids, segment_ids])
  File "D:\anaconda\envs\py37tf14gpu\lib\site-packages\keras\engine\training.py", line 1462, in predict
    callbacks=callbacks)
  File "D:\anaconda\envs\py37tf14gpu\lib\site-packages\keras\engine\training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "D:\anaconda\envs\py37tf14gpu\lib\site-packages\tensorflow\python\keras\backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "D:\anaconda\envs\py37tf14gpu\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas xGEMMBatched launch failed : a.shape=[12,10,64], b.shape=[12,64,10], m=10, n=10, k=64, batch_size=12
	 [[{{node Transformer-0-MultiHeadSelfAttention/einsum/MatMul}}]]
	 [[lambda_1/strided_slice/_1231]]
  (1) Internal: Blas xGEMMBatched launch failed : a.shape=[12,10,64], b.shape=[12,64,10], m=10, n=10, k=64, batch_size=12
	 [[{{node Transformer-0-MultiHeadSelfAttention/einsum/MatMul}}]]
0 successful operations.
0 derived errors ignored.

Process finished with exit code 1

```

### 自我尝试
装了好多python和tf-gpu版本，用conda装cuda和cudnn，手动装cuda打补丁什么都试过了，就是不行，后来查到可能是显卡版本太新了，有没有什么办法解决呢

**Comment by lancelotleod** [comment]
今天看到以前有人问过这个问题了，使用docker版的nvidia-tensorflow:22.02解决了这个问题
