### ISSUE TITLE
跑task_relation_extraction.py这个模型报的错,TypeError: object.__init__() takes no parameters大佬帮忙看看

### ISSUE THREAD

**Issue by a461925358** [bojone/bert4keras#54]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "D:/pycharm/bert4keras/examples/task_relation_extraction.py", line 323, in <module>
    callbacks=[evaluator, EMAer])
  File "E:\Anaconda\envs\keras\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "E:\Anaconda\envs\keras\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "E:\Anaconda\envs\keras\lib\site-packages\keras\engine\training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "E:\Anaconda\envs\keras\lib\site-packages\keras\callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "D:/pycharm/bert4keras/examples/task_relation_extraction.py", line 305, in on_epoch_end
    f1, precision, recall = evaluate(valid_data)
  File "D:/pycharm/bert4keras/examples/task_relation_extraction.py", line 272, in evaluate
    R = set([SPO(spo) for spo in extract_spoes(d['text'])])
  File "D:/pycharm/bert4keras/examples/task_relation_extraction.py", line 272, in <listcomp>
    R = set([SPO(spo) for spo in extract_spoes(d['text'])])
  File "D:/pycharm/bert4keras/examples/task_relation_extraction.py", line 251, in __init__
    super(SPO, self).__init__(spo)
TypeError: object.__init__() takes no parameters
0it [00:03, ?it/s]

**Comment by bojone** [comment]
麻烦先将task_relation_extraction.py同步到最新版本。
