### ISSUE TITLE
跑task_relation_extraction.py这个模型,batch_size改成32之后，出现Incompatible shapes：[32,128,768]vs[32,256,768],请帮忙指教一下是不是layer_normalization哪里设置固定了maxlen的部分

### ISSUE THREAD

**Issue by htt860823** [bojone/bert4keras#56]

**Comment by bojone** [comment]
哪一行？能否贴详细一点？

**Comment by htt860823** [comment]
Epoch 1/20
Traceback (most recent call last):
  File "/home/Desktop/Entity-Relation-Extraction-master/task_relation_extraction.py", line 314, in <module>
    callbacks=[evaluator,EMAer])
  File "/home/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/.local/lib/python3.6/site-packages/keras/engine/training_generator.py", line 191, in fit_generator
    class_weight=class_weight)
  File "/home/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1220, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2661, in __call__
    return self._call(inputs)
  File "/home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2631, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/home/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [32,128,768] vs. [32,256,768]
	 [[Node: layer_normalization_1/mul = Mul[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/layer_normalization_1/mul_grad/Reshape_1"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](Encoder-12-FeedForward-Norm/truediv, layer_normalization_1/add_1)]]
	 [[Node: loss/add/_5477 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_21607_loss/add", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by htt860823** [comment]
只是把源代码中task_relation_extraction.py的第24行的batch_size=64换成32了，谢谢指教！

**Comment by bojone** [comment]
我刚试了一下，batch size=32跑了几百步，并没有发现任何错误。

**Comment by htt860823** [comment]
找到了问题keras版本的问题

**Comment by bojone** [comment]
之前用哪个keras版本？

**Comment by htt860823** [comment]
2.2.0

**Comment by wangxiaoqing1112** [comment]
我的keras是2.3.1也出现该问题
--------------------------------------------
Epoch 1/6
2021-03-16 14:21:34.881663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
Traceback (most recent call last):
  File "bert_similarly.py", line 149, in <module>
    callbacks=[evaluator]
  File "/home/wuming/software/anaconda3/envs/myKeras/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/wuming/software/anaconda3/envs/myKeras/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/wuming/software/anaconda3/envs/myKeras/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/home/wuming/software/anaconda3/envs/myKeras/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/wuming/software/anaconda3/envs/myKeras/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/wuming/software/anaconda3/envs/myKeras/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [30522,768] vs. [21128,768]
         [[{{node training/Adam/sub_4}}]]
