### ISSUE TITLE
AttributeError: Can't pickle local object 'parallel_apply.<locals>.worker_step'

### ISSUE THREAD

**Issue by a461925358** [bojone/bert4keras#62]
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\ccd\AppData\Local\Temp\jieba.cache
Loading model cost 0.625 seconds.
Prefix dict has been built succesfully.
0it [00:00, ?it/s]Traceback (most recent call last):
  File "F:/pycharm/bert4keras/pretraining/data_utils.py", line 344, in <module>
    max_queue_size=max_queue_size,
  File "F:/pycharm/bert4keras/pretraining/data_utils.py", line 126, in process
    callback=write_to_tfrecord,
  File "F:\pycharm\bert4keras\bert4keras\snippets.py", line 105, in parallel_apply
    pool = Pool(workers, worker_step, (in_queue, out_queue))
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\software\anoconda\envs\keras_bert\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'parallel_apply.<locals>.worker_step'

**Comment by bojone** [comment]
不支持windows。

如果非要跑windows，请给`parallel_apply`传`dummy=True`参数
