### ISSUE TITLE
[0.5.9] 多GPU fine-tune ALBERT模型时报错。

### ISSUE THREAD

**Issue by duanxingjian** [bojone/bert4keras#85]
您好，我想使用两个GPU fine-tune task_sentiment_albert.by，于是添加了几行代码：
```
from keras.utils import multi_gpu_model
....
model = keras.models.Model(bert.model.input, output)
model = multi_gpu_model(model, gpus=2)
```
昨天升级bert4keras至0.5.9后出现此问题，我在0.5.8版里运行正常。
错误信息：
527/528 [============================>.] - ETA: 0s - loss: 0.4247 - accuracy: 0.7977Traceback (most recent call last):
  File "/home/yifengjinke/repos/albert_zh/task_sentiment_albert.py", line 126, in <module>
    callbacks=[evaluator])
  File "/home/yifengjinke/repos/bert/venv2/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yifengjinke/repos/bert/venv2/lib/python3.6/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yifengjinke/repos/bert/venv2/lib/python3.6/site-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/home/yifengjinke/repos/bert/venv2/lib/python3.6/site-packages/keras/engine/training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/yifengjinke/repos/bert/venv2/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "/home/yifengjinke/repos/bert/venv2/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [10,12,128,128] vs. [9,1,1,128]
	 [[{{node replica_1/model_2/Transformer-MultiHeadSelfAttention/sub_1}}]]
  (1) Invalid argument: Incompatible shapes: [10,12,128,128] vs. [9,1,1,128]
	 [[{{node replica_1/model_2/Transformer-MultiHeadSelfAttention/sub_1}}]]
	 [[training/new_optimizer/gradients/AddN_86/_1009]]
0 successful operations.
1 derived errors ignored.

Process finished with exit code 1

**Comment by bojone** [comment]
keras的multi_gpu_model不大正常，经常还不生效，推荐用tf.keras的分布式策略

**Comment by fengxin619** [comment]
这个问题有解决方案了么？ 除了使用tf.distribute.MirroredStrategy

**Comment by bojone** [comment]
> 这个问题有解决方案了么？ 除了使用tf.distribute.MirroredStrategy

为什么要除了...
