### ISSUE TITLE
tensorflow 2.0 run task_sequence_labeling_ner_crf.py 报错

### ISSUE THREAD

**Issue by w1994wl202** [bojone/bert4keras#88]
1/86 [..............................] - ETA: 7:34:36Traceback (most recent call last):
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: Transformer-11-FeedForward-Add/All:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/test/app/src/task_sequence_labeling_ner_crf.py", line 227, in <module>
    callbacks=[evaluator])
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 1306, in fit_generator
    initial_epoch=initial_epoch)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/data/py3_5env/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'Transformer-11-FeedForward-Add/All:0' shape=(None, None) dtype=bool>]

Process finished with exit code 1

另外，之前named_entity_recognize中nodes = model.predict([[token_ids],[segment_ids]])[0]也报错，改为nodes = model.predict([np.array([token_ids]), np.array([segment_ids])])[0]后正常运行

**Comment by bojone** [comment]
优先支持keras，次之是tf 1.x的tf.keras，tf 2.0随缘～

**Comment by HellowDream** [comment]
楼主这个问题有什么解决思路吗？我也遇到了一模一样的问题，但是感觉自定义层挺符合tf2.0要求。。不该有毛病的

**Comment by Qinbf** [comment]
这是tf2动态图机制导致的问题，在实际模型计算的过程中不能存在keras的symbolic tensors，得是实际数值。可以参考我的pull requests看看。
