### ISSUE TITLE
run task_sequence_labeling_ner_crf.py Error:Error when checking target: expected conditional_random_field_1 to have 3 dimensions, but got array with shape (32, 23)

### ISSUE THREAD

**Issue by w1994wl202** [bojone/bert4keras#95]
苏神，您好，我用运行 task_sequence_labeling_ner_crf.py 报错，tensorflow版本是 1.14
Traceback (most recent call last):
  File "/data/test/app/src/sequence_labeling.py", line 223, in <module>
    callbacks=[evaluator])
  File "/data/py3_5env/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/data/py3_5env/lib/python3.6/site-packages/keras/engine/training.py", line 2096, in fit_generator
    class_weight=class_weight)
  File "/data/py3_5env/lib/python3.6/site-packages/keras/engine/training.py", line 1808, in train_on_batch
    check_batch_axis=True)
  File "/data/py3_5env/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/data/py3_5env/lib/python3.6/site-packages/keras/engine/training.py", line 141, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected conditional_random_field_1 to have 3 dimensions, but got array with shape (32, 23)

**Comment by bojone** [comment]
您好，我用运行 task_sequence_labeling_ner_crf.py 没报错，tensorflow版本是 1.14

**Comment by Chuanyunux** [comment]
我也遇到了类似的问题：

_ValueError: Cannot feed value of shape (32, 130) for Tensor 'conditional_random_field_1_target:0', which has shape '(?, ?, ?)'_

看起来是生成器生成训练数据的时候labels的shape和最后一层crf输出的shape不一致，我在data_generator类里倒数第二行reshape了一下生成的bath_labels，代码就运行正常了，像这样：

      yield [batch_token_ids, batch_segment_ids], np.reshape(batch_labels,(batch_size, -1, batch_labels.shape[1]))

**Comment by w1994wl202** [comment]
@bojone 感谢指教，现在找到原因是我Keras版本不对，之前Keras版本是2.1.0，升级到2.2.0就没有报错问题。抱歉打扰了。
