### ISSUE TITLE
运行pretraining,使用gpt报错'Tensor' object has no attribute '_keras_history'

### ISSUE THREAD

**Issue by Mars-1990** [bojone/bert4keras#97]
报错信息如下：
Traceback (most recent call last):
  File "pretraining.py", line 237, in <module>
    train_model = build_bert_model_for_pretraining()
  File "pretraining.py", line 196, in build_bert_model_for_pretraining
    bert, train_model, loss = build_bert_model_with_lm()
  File "pretraining.py", line 173, in build_bert_model_with_lm
    lm_loss = Lambda(lm_loss, name='lm_loss')([token_ids, proba])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/core.py", line 785, in call
    return self.function(inputs, **arguments)
  File "pretraining.py", line 152, in lm_loss
    mask = search_layer(y_pred, 'Embedding-Token').output_mask
  File "/usr/local/lib/python3.5/dist-packages/bert4keras/backend.py", line 88, in search_layer
    layer = inputs._keras_history[0]
AttributeError: 'Tensor' object has no attribute '_keras_history'

**Comment by ExpressGit** [comment]
??? 这个问题是怎么解决的
